FROM pypy:3.7

WORKDIR /rollercoaster

COPY requirements-pypy.txt .
RUN pip install --no-cache-dir -r requirements-pypy.txt

COPY input /rollercoaster/input
COPY scripts /rollercoaster/scripts
COPY simulation /rollercoaster/simulation
COPY tests /rollercoaster/tests
COPY *.py /rollercoaster/
COPY *.ipynb /rollercoaster/
